postgres-operator:
  enabled: true
  configKubernetes:
    enable_cross_namespace_secret: true

managedPostgres:
  enabled: true
  config:
    volume:
      storageClass: "local-path"
    users:
      keycloak:
        - createdb
    databases:
      keycloak: keycloak

vcverifier:
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.tls: "true"
    tls:
      - hosts:
          - verifier.org
        secretName: tls-secret
    hosts:
      - host: verifier.org
        paths:
          - "/"
  deployment:
    image:
      tag: au
      pullPolicy: Always
    logging:
      level: DEBUG
    verifier:
      tirAddress: https://tir.127.0.0.1.nip.io/
      did: grafana-oauth
      supportedModes: ["byValue","byReference"]
      clientIdentification:
        keyPath: /signing-key/client.key.pem
        requestKeyAlgorithm: ES256
        id: x509_san_dns:verifier.org
        certificatePath: /certificate/client-chain-bundle.cert.pem
    server:
      host: https://verifier.org
    configRepo:
      configEndpoint: http://credentials-config-service:8080
    additionalVolumes:
      - name: signing-key
        secret:
          secretName: signing-key
      - name: cert-chain
        secret:
          secretName: cert-chain
      # add the self generated root ca to the system truststore
      - name: root-ca
        emptyDir: {}
      - name: ca-to-add
        secret:
          secretName: root-ca
    additionalVolumeMounts:
      - name: signing-key
        mountPath: /signing-key
      - name: cert-chain
        mountPath: /certificate
      # add the self generated root ca to the system truststore
      - name: root-ca
        mountPath: /etc/ssl/cert.pem
        subPath: cert.pem
    additionalEnvVars:
      - name: HTTPS_PROXY
        value: "http://squid-proxy.infra.svc.cluster.local:8888"
      - name: HTTP_PROXY
        value: "http://squid-proxy.infra.svc.cluster.local:8888"
      - name: NO_PROXY
        value: "credentials-config-service,w3.org,trusted-issuers-list"
    initContainers:
      # add the self generated root ca to the system truststore
      - name: add-root-ca
        image: alpine:3.21.3
        command:
          - /bin/sh
        args:
          - -c
          - |
            #!/bin/sh
            cp /etc/ssl/cert.pem /root-ca/cert.pdata.typeem
            cat /root-ca/cacert.pem >> /root-ca/cert.pem
        volumeMounts:
          - name: root-ca
            mountPath: /root-ca
          - name: ca-to-add
            mountPath: /root-ca/cacert.pem
            subPath: cacert.pem


trusted-issuers-list:
  ingress:
    tir:
      enabled: true
      hosts:
        - host: tir.127.0.0.1.nip.io
    til:
      enabled: true
      hosts:
        - host: til.127.0.0.1.nip.io

credentials-config-service:
  deployment:
    image:
      tag: 3.4.2-PRE-27
  registration:
    enabled: true
    services:
      - id: data-service
        defaultOidcScope: "default"
        authorizationType: "FRONTEND_V2"
        oidcScopes:
          "default":
            credentials:
              - type: UserCredential
                trustedParticipantsLists: []
                trustedIssuersLists:
                  - http://trusted-issuers-list:8080
                jwtInclusion:
                  enabled: true
                  fullInclusion: true