apiVersion: v1
data:
  client-pkcs8.key.pem: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ1BnbjUyTVBEMUFJeWU2NS8KNnlqanFnNGtOU20ydnNRNFJTWWtRVHdYdlJLaFJBTkNBQVR4VXV2cCs1UGN2RDQ0dVFNREkzSDRxTmNWNUJJNwpQMnBaS1pzVWFzNUpyVXVwblBhQUlxd3o5ek80cnRsVmtUNmNUSUF0NWo3eUNUcmZtSVhqQWtaOAotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  client.key.pem: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUQ0SitkakR3OVFDTW51dWYrc280Nm9PSkRVcHRyN0VPRVVtSkVFOEY3MFNvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFOFZMcjZmdVQzTHcrT0xrREF5TngrS2pYRmVRU096OXFXU21iRkdyT1NhMUxxWnoyZ0NLcwpNL2N6dUs3WlZaRStuRXlBTGVZKzhnazYzNWlGNHdKR2ZBPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  creationTimestamp: null
  name: signing-key
